### ISSUE TITLE
won't build on Ubuntu 22.04 with soapysdr

### ISSUE THREAD

**Issue by godfuzz3r** [myriadrf/srsLTE#8]
Hi, thank you for you fork. I noticed linkage error on Ubuntu 22.04 if both soapysdr and native lime plugins are enabled:
```
48.82 /usr/bin/ld: ../../lib/src/phy/rf/libsrsran_rf_lime.a(rf_lime_imp.c.o):(.bss+0x0): multiple definition of `zero_mem'; ../../lib/src/phy/rf/libsrsran_rf_soapy.a(rf_soapy_imp.c.o):(.bss+0x0): first defined here
49.16 collect2: error: ld returned 1 exit status
49.17 make[3]: *** [srsenb/src/CMakeFiles/srsenb.dir/build.make:232: srsenb/src/srsenb] Error 1
49.17 make[2]: *** [CMakeFiles/Makefile2:12145: srsenb/src/CMakeFiles/srsenb.dir/all] Error 2
49.17 make[1]: *** [CMakeFiles/Makefile2:12152: srsenb/src/CMakeFiles/srsenb.dir/rule] Error 2
49.17 make: *** [Makefile:4476: srsenb] Error 2
```

Here is my dockerfile:
```
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# UHD/lime drivers
RUN apt update && apt install -y --no-install-recommends \
    --no-install-suggests \
    soapysdr-tools libsoapysdr-dev \
    liblimesuite-dev \
    uhd-host libuhd-dev \
    # build deps
    git cmake libfftw3-dev libmbedtls-dev libboost-program-options-dev libconfig++-dev libsctp-dev \
    libzmq3-dev libboost-system-dev libboost-test-dev libboost-thread-dev \
    g++ make pkg-config libpython2-dev swig libi2c-dev \
    libboost-program-options-dev libconfig++-dev libusb-1.0-0-dev swig \
    && rm -rf /var/lib/apt/lists/*


ENV UHD_IMAGES_DIR=/usr/share/uhd/images/

RUN uhd_images_downloader

# Get srsLTE, compile and install
RUN git clone https://github.com/myriadrf/srsRAN_4G.git

WORKDIR /srsRAN_4G

RUN git checkout lc/main

RUN mkdir build && cd build && \
    cmake -DUSE_LTE_RATES=true ../ && make -j$(nproc) srsenb && \
    make install && \
    ldconfig

ENTRYPOINT ["bash", "/mnt/entrypoint.sh"]
```

All compiles and works ok if packages `soapysdr-tools libsoapysdr-dev` are not installed.

Usage of both native lime and soapy could be helpful for support lime and other SDR's like blade in the same setup.

Let me know if you want any additional information.
